exclude: [ "README.md", "Gemfile", "Gemfile.lock", ".idea", "bower_components", "node_modules" ]

name: "Infinates"
description: "A blogging group"

url: "http://localhost:4000"

logoPath: "/lib/logo.png"

markdown: rdiscount
permalink: pretty

paginate: 5

authors:
  tcd:
    displayName: The Code Destroyer
    bio: dsfdfds
    gravatar: 8b2576c1371a08fb6167c09a33ae50e8
    email: the.code.destroyer@gmail.com
    web: https://thecodedestroyer.github.com/
    twitter: thcodedestroyer
    github: thecodedestroyer
  majcn:
    displayName: Gregor Majcen
    bio: dsfdfds
    gravatar: ????
    email: majcn@gmail.com
    web: https://majcn.github.com/
    twitter: majcn
    github: majcn