exclude: [ "README.md", "package.json", "Gruntfile.js", "lib/src", "CNAME", "Gemfile", "Gemfile.lock", ".idea", "node_modules" ]

name: "Coding 4 Passion"
description: "A blogging group"
url: "http://coding4passion.org"
logoPath: "/lib/assets/logo.png"

# Social
facebook: "https://www.facebook.com/coding4passion"
google: "https://plus.google.com/+Coding4passionOrg"
twitter: "https://twitter.com/coding4passion"
github: "https://github.com/Coding4Passion"
feed: "http://feeds.feedburner.com/Coding4Passion"

markdown: rdiscount
permalink: pretty

paginate: 5

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      postType: "featured, banner"

authors:
  tcd:
    displayName: Nace Logar
    bio: "My name is Nace, pronounced 'Natse' I started as a windows desktop developer.Later on I became web developer working primarily on web pages and business web applications where I actually fell in love with CSS, HTML and JS."
    gravatar: 8b2576c1371a08fb6167c09a33ae50e8
    email: the.code.destroyer@gmail.com
    web: http://thecodedestroyer.com/
    twitter: thcodedestroyer
    github: thecodedestroyer
  majcn:
    displayName: Gregor Majcen
    bio: dsfdfds
    gravatar: c9376838a0f0962e333c4bd5ed289163
    email: majcn.m@gmail.com
    web: https://majcn.github.com
    twitter: majcnM
    github: majcn
  ym:
    displayName: Yuri Makassiouk
    bio: "His brain-care specialist, Gag Halfrunt, also said, 'Vell, Yuri's just zis guy, you know?'"
    gravatar: 404bf4f935286b6be33c6a5fa393721d
    email: makassiouk@gmail.com
    web: no.linkedin.com/in/makassiouk
    github: left-semi-join