exclude: [ "README.md", "Gemfile", "Gemfile.lock", ".idea", "bower_components", "node_modules" ]

name: "Infinates"
description: "A blogging group"

url: "http://infinates.com"
logoPath: "/lib/logo_black.png"

markdown: rdiscount
permalink: pretty

paginate: 11

authors:
  tcd:
    displayName: The Code Destroyer
    bio: dsfdfds
    gravatar: ????
    email: the.code.destroyer@gmail.com
    web: https://thecodedestroyer.github.com/
    twitter: thcodedestroyer
    github: thecodedestroyer
  majcn:
    displayName: Gregor Majcen
    bio: dsfdfds
    gravatar: ????
    email: majcn@gmail.com
    web: https://majcn.github.com/
    twitter: majcn
    github: majcn